#!/bin/sh /etc/rc.common

START=99

PROG=/usr/bin/ffmpeg

USE_PROCD=1

ffmpeg_start(){
	local enabled="$(uci get ffmpeg.ffmpeg.enabled)";
	if [ "$enabled" == "1" ] || [ "$enabled" == "true" ];then
		local in_dev="$(uci get ffmpeg.ffmpeg.in_device)";
		local framerate="$(uci get ffmpeg.ffmpeg.framerate)";
		local resolution="$(uci get ffmpeg.ffmpeg.resolution)";
		local out_vcodec="$(uci get ffmpeg.ffmpeg.vcodec)";
		local b_v="$(uci get ffmpeg.ffmpeg.b_v)";
		local remote="$(uci get ffmpeg.ffmpeg.remote)";
		local override_ffserver="$(uci get ffmpeg.ffmpeg.override_ffserver)";
#		local in_pix_fmt="$(uci get ffmpeg.ffmpeg.input_pix_format)";
		local in_pix_fmt="uyvy422"; #On i.mx6ull with ov5640 only this is aplicable
		
		local args="";
		
		args=" -s $resolution -r $framerate";
		#framerate before input dev sets device framerate ov5640 supports only one of 15 or 30.
		args="$args -framerate 15 ";
		#i.mx6ull driver supports only uyvy422
		args="$args -input_format $in_pix_fmt";
		args="$args -i $in_dev";
		#output framerate, only used for proper timing in output stream
		args="$args -framerate $framerate"
		args="$args -vcodec $out_vcodec";
		args="$args -b:v $b_v";
		if [ "$override_ffserver" == "1" ] || [ "$override_ffserver" == "true" ];then
			args="$args -override_ffserver";
		fi;
		args="$args $remote";
		
		procd_open_instance;
		procd_set_param command $PROG $args;
		procd_set_param respawn;
		procd_close_instance;
	
	fi
}


service_triggers(){
	procd_add_reload_trigger "ffmpeg"
}

start_service(){
	ffmpeg_start;
}

